# Generated by Django 5.1 on 2024-08-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecommerceApp', '0002_alter_tienda_id_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/'),
        ),
    ]
