# Generated by Django 5.1 on 2024-08-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecommerceApp', '0008_remove_solicitud_id_usuario_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='id_usuario_modificacion',
        ),
    ]
