# Generated by Django 5.1 on 2024-08-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecommerceApp', '0011_reseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='tienda',
            new_name='id_tienda',
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='usuario',
            new_name='id_usuario_creacion',
        ),
    ]
