# Generated by Django 5.1 on 2024-08-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecommerceApp', '0012_rename_tienda_reseña_id_tienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='calificacion',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
