# Generated by Django 5.1 on 2024-08-29 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecommerceApp', '0013_reseña_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='id_tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='onlinecommerceApp.tienda'),
        ),
    ]
