# Generated by Django 5.1 on 2024-09-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecommerceApp', '0002_alter_producto_fecha_creacion_and_more'),
        ('onlinecommerceApp', '0014_alter_reseña_id_tienda'),
    ]

    operations = [
    ]
