# Generated by Django 5.1 on 2024-09-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecommerceApp', '0016_remove_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
