# Generated by Django 5.0.7 on 2024-08-22 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_modificado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
