# Generated by Django 5.1 on 2024-08-24 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecommerceApp', '0003_alter_tienda_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_modificacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
